
;****************************************************************************
;                      WARNING: DO NOT EDIT THIS SECTION!                    
;      This section gets automatically generated by the Resource Editor      
;   And any data here will get overwritten, when the resources are updated   
;****************************************************************************
; [RESOURCES SECTION                                                         
; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\player><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : player
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
player:
; pixels and mask bit pairs
defb   0,   0
defb 127, 254
defb 127, 254
defb 127, 254
defb 125, 190
defb 125, 190
defb 125, 190
defb 127, 254
defb 127, 254
defb 127, 254
defb 111, 246
defb 111, 246
defb  96,   6
defb 127, 254
defb 127, 254
defb   0,   0
; attrs
defb   6,   6
defb   6,   6
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\player>]             

; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\troll><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : troll
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
troll:
; pixels and mask bit pairs
defb   7, 224
defb  15, 240
defb  24,  24
defb 213, 171
defb 239, 247
defb 185, 157
defb 124,  62
defb  63, 252
defb  88,  26
defb 239, 247
defb 240,  15
defb 239, 247
defb  11, 208
defb 237, 183
defb  14, 112
defb  30, 120
; attrs
defb  66,  66
defb   2,   2
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\troll>]              

; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\dwarf><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : dwarf
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
dwarf:
; pixels and mask bit pairs
defb   1,   0
defb   3, 128
defb   3, 128
defb   7, 192
defb   7, 192
defb   7, 192
defb  15, 224
defb  15, 224
defb  31, 240
defb  13,  96
defb   5,  64
defb  23, 208
defb  59, 184
defb  84,  84
defb  39, 200
defb  14, 224
; attrs
defb  66,  66
defb  70,  70
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\dwarf>]              

; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\elf_mage><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : elf_mage
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
elf_mage:
; pixels and mask bit pairs
defb   3, 131
defb  63, 251
defb  29, 113
defb   7, 193
defb   2, 130
defb   3, 130
defb  13,  98
defb  26, 180
defb  55, 220
defb  43, 172
defb 107, 172
defb 104,  44
defb 103, 212
defb 118, 204
defb 116,  92
defb   4,  80
; attrs
defb  67,  67
defb   3,   3
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\elf_mage>]           

; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\goblin_brute><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : goblin_brute
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
goblin_brute:
; pixels and mask bit pairs
defb   0,   0
defb 231,   8
defb 127, 176
defb  61, 192
defb  12, 132
defb  31, 226
defb  95, 115
defb  95, 179
defb 108,  70
defb 231, 166
defb 200, 108
defb 207,  56
defb  30, 128
defb  57, 208
defb  32,  64
defb 112, 112
; attrs
defb   4,   4
defb   4,   4
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\goblin_brute>]       

; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\sprite><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : sprite
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
sprite:
; pixels and mask bit pairs
defb  32,  33
defb  32, 227
defb  51, 198
defb  50, 142
defb  27,  60
defb  29, 156
defb  11, 232
defb   7, 176
defb  69, 200
defb  41, 228
defb  17, 240
defb   9, 248
defb   1, 128
defb   0,  72
defb   0,  36
defb   0,   0
; attrs
defb  69,  69
defb  69,  69
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\sprite>]             

; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite>]                    

; ]RESOURCES SECTION                                                         