                                                     
;****************************************************************************
;                      WARNING: DO NOT EDIT THIS SECTION!                    
;      This section gets automatically generated by the Resource Editor      
;   And any data here will get overwritten, when the resources are updated   
;****************************************************************************
; [RESOURCES SECTION                                                         
; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\player><Data:ScanlinesRowColumn:XChar:YChar:MaskAfter:MaskInvert:UseAttributes>]
; Name   : player
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
player:
; pixels and mask bit pairs
defb   0,   0
defb 127, 254
defb 127, 254
defb 127, 254
defb 125, 190
defb 125, 190
defb 125, 190
defb 127, 254
defb 127, 254
defb 127, 254
defb 111, 246
defb 111, 246
defb  96,   6
defb 127, 254
defb 127, 254
defb   0,   0
; attrs
defb   6,   6
defb   6,   6
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite\player>]             

; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Sprite>]                    

; ]RESOURCES SECTION                                                         
