                                                       
;****************************************************************************
;                      WARNING: DO NOT EDIT THIS SECTION!                    
;      This section gets automatically generated by the Resource Editor      
;   And any data here will get overwritten, when the resources are updated   
;****************************************************************************
; [RESOURCES SECTION                                                         
; [RESOURCE: <Parser:String Tables><Resource:String Tables\All String Tables><Data:>]
;
; STRING TABLES
;

;
; String Table: strings
;
strings:
defw INTRODUCTION

;
; STRINGS
;
INTRODUCTION:         defb $48,$65,$6C,$6C,$6F,$20,$47,$61,$6D,$65,$73,$21,$00
; ]RESOURCE: <Parser:String Tables><Resource:String Tables\All String Tables>]

; ]RESOURCE: <Parser:String Tables><Resource:String Tables>]                  

; ]RESOURCES SECTION                                                         
