
;****************************************************************************
;                      WARNING: DO NOT EDIT THIS SECTION!                    
;      This section gets automatically generated by the Resource Editor      
;   And any data here will get overwritten, when the resources are updated   
;****************************************************************************
; [RESOURCES SECTION                                                         
; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Tile\bush><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : bush
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
bush:
; pixels and mask bit pairs
defb  48, 128
defb  25, 198
defb 109, 238
defb  49, 206
defb  22, 212
defb 199,  56
defb 119, 188
defb 122,  94
defb  56, 239
defb   6, 224
defb 110, 206
defb 220, 182
defb 155,  59
defb  19, 184
defb   3, 156
defb   1,   4
; attrs
defb 196, 196
defb 196, 196
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Tile\bush>]                 

; [RESOURCE: <Parser:ZX Spectrum Images><Resource:Tile\blank><Data:ScanlinesRowColumn:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : blank
; Size   : 16x16
; Palette: ZX Spectrum
; Masked : No
; RowOrder: Classic
blank:
; pixels and mask bit pairs
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
defb   0,   0
; attrs
defb   0,   0
defb   0,   0
; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Tile\blank>]                

; ]RESOURCE: <Parser:ZX Spectrum Images><Resource:Tile>]                      

; ]RESOURCES SECTION                                                         
